embedding_model_name: "text-embedding-ada-002"
max_tokens: 4096

llm_config: 
  llm_system_role: "You are a helpful assistant. Use the following context to answer the question."


llm_model_name: "gpt-3.5-turbo"
temperature: 0.7
max_token: 1500



